### ISSUE TITLE
统计图

### ISSUE THREAD

**Issue by xuyongy** [xuyongy/Biostatistics#4]
### 150人的红细胞计数 
数据来源：生物医学统计工作室（https://raw.githubusercontent.com/xuyongy/Getdata/master/RBC.csv）

**rurl<-'https://raw.githubusercontent.com/xuyongy/Getdata/master/RBC.csv'
dat <- read.csv(rurl,header = T)
summary(dat)**

rbc       
Min.   :3.790  
1st Qu.:4.540  
Median :4.800  
Mean   :4.793  
3rd Qu.:5.040  
Max.   :5.880

### 频数分布图

**hist(dat$rbc)**
![image](https://user-images.githubusercontent.com/49633269/56180964-1c447c80-603e-11e9-8b55-b39385f9761e.png)

**Comment by xuyongy** [comment]
![老鼠](https://user-images.githubusercontent.com/49633269/56172338-91528a80-601b-11e9-816f-8736c5c69e5b.jpg)

**Comment by NWUSTAT** [comment]
### 这是什么图？

**Comment by xuyongy** [comment]
### 圆图             

**child <- c(0.168, 0.184, 0.333, 0.153,0.162)              
names(child) <- c("0-2岁(16.8%)", "3-5岁(18.4%)", "6-11岁(33.3%)", "12-14岁(15.3%)","15-17岁（16.2%）")           
pie(child, clockwise=T,col = c("red","red","green","blue","yellow"),main="图1 中国0-17岁儿童构成（2015年)")**          

![image](https://user-images.githubusercontent.com/49633269/56296256-b1d82d00-6160-11e9-8d26-d014281d9631.png)
