### ISSUE TITLE
练习题

### ISSUE THREAD

**Issue by NWUSTAT** [xuyongy/Biostatistics#5]
M001（多选题）           
**描述一组数据（如亩产量）集中趋势的指标有（A  B  C  D  E）**          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;A 均数        &#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp; &#160;&#160;&nbsp;&nbsp; &#160;&nbsp;&#160;&#160;&nbsp;&nbsp;B 四分位数          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;C 几何均数          &#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp; D 中位数          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;E 变异系数

**Comment by xuyongy** [comment]
S001（单选题）
**根据样本计算的样本均数的95%置信区间说明（A B C D E）**          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;A 本次抽样95%的观察值的波动范围          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;B 95%的样本均数在此区间          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;C 重复抽样总体均数在此区间的概率是95%          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;D 再次抽样的样本均数在此区间的概率是95%          
&#160;&#160;&nbsp;&nbsp;&#160;&#160;&nbsp;&nbsp;&#160;&#160;E 总体均数95%的波动范围
