### ISSUE TITLE
卡方检验

### ISSUE THREAD

**Issue by xuyongy** [xuyongy/Biostatistics#7]
### 卡方检验-R           

1.创建一个2列的二维表 Table 1
        
**>matrix(c(15,23,24,12,12,21),nc=2)->Table1**       
**>Table1**   
    
&#160;&#160;&#160;&#160;&#160;[,1] [,2]      
[1,]   15   12
[2,]   23   12
[3,]   24   21  
            
2.计算校正的卡方值 
         
**>chisq.test(Table1,correct=TRUE)**       
      
Pearson's Chi-squared test       
data:  Table1       
X-squared = 1.3229, df = 2, p-value = 0.5161

**Comment by xuyongy** [comment]
### 卡方检验-SPSS Syntax             

1.输入数据（把数据放进数据区）

**DATA LIST Free/r c n.          
Begin data.**
1 1 15    
1 2 12      
2 1 23      
2 2 12
3 1 24
3 2 21        
**End data.**    
##三个变量名r，c，n 分别代表二维表的行、列和频数   
![image](https://user-images.githubusercontent.com/49633269/56256727-76a41280-60fc-11e9-8c62-5ba4c6882b1f.png)

2.二维表数据加权 
         
**WEIGHT BY n.**       
      
3.计算卡方值          

 **CROSSTABS 
  /TABLES=r BY c 
  /FORMAT=AVALUE TABLES 
  /STATISTICS=CHISQ 
  /CELLS=COUNT 
  /COUNT ROUND CELL.**
![image](https://user-images.githubusercontent.com/49633269/56257188-f8487000-60fd-11e9-866b-44254f2c64cb.png)

**Comment by xuyongy** [comment]
### 卡方检验-SAS code            

1.输入数据       

**data one;
input r c n @@;
cards;
1 1 15  
1 2 12 
2 1 23      
2 2 12
3 1 24
3 2 21
;**       
/*三个变量名r，c，n 分别代表二维表的行、列和频数   
      
2.调用SAS/freq过程，计算卡方值          

**proc freq data=one;
  weight n;
  tables r*c/chisq;
  run;**

![image](https://user-images.githubusercontent.com/49633269/56270569-052e8900-6129-11e9-91b9-add39841a6b8.png)

**Comment by xuyongy** [comment]
### 卡方检验-Stata             

**tabi 15 12\23 12\24 21,chi2**          

![image](https://user-images.githubusercontent.com/49633269/56272354-21ccc000-612d-11e9-9a34-bc5a464435af.png)

**Comment by NWUSTAT** [comment]
👍
